name: Docker Image CI

on:
  push:
    branches: [ "release/*" ]
  pull_request:
    branches: [ "release/*" ]

env:
 LOGIN: ${{ secrets.DOCKER_LOGIN }}
 NAME: ${{ secrets.DOCKER_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login Docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t $LOGIN/$NAME:${{ github.ref_name }} -f Dockerfile .
    - name: Push image to docker.io
      run: docker push $LOGIN/$NAME:${{ github.ref_name }}
